language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
sudo: false

script:
  - |
    version=1.0.0
    if [ -z "$TRAVIS_TAG" ]; then
      version="$version-pre${TRAVIS_BUILD_NUMBER}"
    fi
    dotnet pack /p:PackageVersion=${version}
  - ls -lhR

deploy:
  provider: script
  skip_cleanup: true
  script: /bin/bash -v -c 'dotnet nuget push -k $NUGET_API_KEY -s https://www.nuget.org **/bin/Debug/*.nupkg'
  on:
    tags: true
    branch: master
    repo: glassechidna/HttpClientMiddleware
