language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
sudo: false

script:
  - |
    version=1.0.2
    if [ -z "$TRAVIS_TAG" ]; then
      version="$version-pre${TRAVIS_BUILD_NUMBER}"
    fi
    dotnet pack /p:PackageVersion=${version}

deploy:
  provider: script
  skip_cleanup: true
  script: /bin/bash -v -c 'for pkg in $(ls **/bin/Debug/*.nupkg); do dotnet nuget push -k $NUGET_API_KEY -s https://www.nuget.org $pkg; done'
  on:
    tags: true
    branch: master
    repo: glassechidna/HttpClientMiddleware
