language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
sudo: false

script:
  - |
    version=1.0.5
    if [ -z "$TRAVIS_TAG" ]; then
      version="$version-pre${TRAVIS_BUILD_NUMBER}"
    fi
    dotnet pack --include-symbols --include-source /p:PackageVersion=${version}

deploy:
  provider: script
  skip_cleanup: true
  script: /bin/bash -v -c 'ls **/bin/Debug/*.nupkg | xargs -n 1 dotnet nuget push -k $NUGET_API_KEY -s https://www.nuget.org'
  on:
    tags: true
    branch: master
    repo: glassechidna/HttpClientMiddleware
